package cl.falabella.b2b.intol.ws.trl.ce.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-04T16:19:28.324-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/info-cambioestado", name = "InfoCambioEstadoService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.trl.ce.beans.response.ObjectFactory.class, cl.falabella.b2b.intol.ws.trl.ce.beans.request.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoCambioEstadoService {

    @WebResult(name = "info-cambioestado-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-cambioestado-response", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.trl.ce.beans.response.InfoCambioestadoResponse cambioEstado(
        @WebParam(partName = "request", name = "info-cambioestado-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-cambioestado-request")
        cl.falabella.b2b.intol.ws.trl.ce.beans.request.InfoCambioestadoRequest request
    );
}
