package cl.falabella.b2b.intol.ws.infopalet.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Aug 26 14:57:28 CLT 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/info-palet", name = "InfoPaletService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.infopalet.beans.request.ObjectFactory.class, cl.falabella.b2b.intol.ws.infopalet.beans.response.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoPaletService {

    @WebResult(name = "info-palet-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-palet-response", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.infopalet.beans.response.InfoPaletResponse infoPalet(
        @WebParam(partName = "request", name = "info-palet-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-palet-request")
        cl.falabella.b2b.intol.ws.infopalet.beans.request.InfoPaletRequest request
    );
}
