package cl.falabella.b2b.intol.ws.entregadocumento.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Thu Aug 26 14:57:23 CLT 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/entrega-documento", name = "EntregaDocumentoService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.entregadocumento.beans.request.ObjectFactory.class, cl.falabella.b2b.intol.ws.entregadocumento.beans.response.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EntregaDocumentoService {

    @WebResult(name = "entrega-documento-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/entrega-documento-response", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.entregadocumento.beans.response.EntregaDocumentoResponse entregaDocumento(
        @WebParam(partName = "request", name = "entrega-documento-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/entrega-documento-request")
        cl.falabella.b2b.intol.ws.entregadocumento.beans.request.EntregaDocumentoRequest request
    );
}
