package cl.falabella.b2b.intol.ws.adminarchivo.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.10
 * Wed May 09 10:57:53 CLT 2012
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/admin-archivo", name = "AdminArchivoService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.adminarchivo.beans.descarga.response.ObjectFactory.class, cl.falabella.b2b.intol.ws.adminarchivo.beans.carga.response.ObjectFactory.class, cl.falabella.b2b.intol.ws.adminarchivo.beans.descarga.request.ObjectFactory.class, cl.falabella.b2b.intol.ws.adminarchivo.beans.consulta.response.ObjectFactory.class, cl.falabella.b2b.intol.ws.adminarchivo.beans.consulta.request.ObjectFactory.class, cl.falabella.b2b.intol.ws.adminarchivo.beans.carga.request.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdminArchivoService {

    @WebResult(name = "admin-archivo-descarga-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-descarga-response", partName = "response-descarga")
    @WebMethod(operationName = "descarga-archivo")
    public cl.falabella.b2b.intol.ws.adminarchivo.beans.descarga.response.AdminArchivoDescargaResponse descargaArchivo(
        @WebParam(partName = "request-descarga", name = "admin-archivo-descarga-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-descarga-request")
        cl.falabella.b2b.intol.ws.adminarchivo.beans.descarga.request.AdminArchivoDescargaRequest requestDescarga
    );

    @WebResult(name = "admin-archivo-carga-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-carga-response", partName = "response-carga")
    @WebMethod(operationName = "carga-archivo")
    public cl.falabella.b2b.intol.ws.adminarchivo.beans.carga.response.AdminArchivoCargaResponse cargaArchivo(
        @WebParam(partName = "request-carga", name = "admin-archivo-carga-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-carga-request")
        cl.falabella.b2b.intol.ws.adminarchivo.beans.carga.request.AdminArchivoCargaRequest requestCarga
    );

    @WebResult(name = "admin-archivo-consulta-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-consulta-response", partName = "response-consulta")
    @WebMethod(operationName = "consulta-archivo")
    public cl.falabella.b2b.intol.ws.adminarchivo.beans.consulta.response.AdminArchivoConsultaResponse consultaArchivo(
        @WebParam(partName = "request-consulta", name = "admin-archivo-consulta-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/admin-archivo-consulta-request")
        cl.falabella.b2b.intol.ws.adminarchivo.beans.consulta.request.AdminArchivoConsultaRequest requestConsulta
    );
}
