//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.20 at 03:14:02 PM CLT 
//


package cl.falabella.b2b.intol.beans.infopalet;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.falabella.b2b.intol.beans.infopalet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ROWSET_QNAME = new QName("http://b2b.falabella.com/schemas/ol/info-palet-database", "ROWSET");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.falabella.b2b.intol.beans.infopalet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Productos }
     * 
     */
    public Productos createProductos() {
        return new Productos();
    }

    /**
     * Create an instance of {@link RowSet }
     * 
     */
    public RowSet createRowSet() {
        return new RowSet();
    }

    /**
     * Create an instance of {@link F12Row }
     * 
     */
    public F12Row createF12Row() {
        return new F12Row();
    }

    /**
     * Create an instance of {@link ProductoRow }
     * 
     */
    public ProductoRow createProductoRow() {
        return new ProductoRow();
    }

    /**
     * Create an instance of {@link F12 }
     * 
     */
    public F12 createF12() {
        return new F12();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RowSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://b2b.falabella.com/schemas/ol/info-palet-database", name = "ROWSET")
    public JAXBElement<RowSet> createROWSET(RowSet value) {
        return new JAXBElement<RowSet>(_ROWSET_QNAME, RowSet.class, null, value);
    }

}
