//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.20 at 03:14:02 PM CLT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://b2b.falabella.com/schemas/ol/info-palet-database", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cl.falabella.b2b.intol.beans.infopalet;
