//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.20 at 03:14:02 PM CLT 
//


package cl.falabella.b2b.intol.beans.infopalet;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for row complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="row">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;group ref="{http://b2b.falabella.com/schemas/ol/info-palet-database}paletGroup"/>
 *           &lt;group ref="{http://b2b.falabella.com/schemas/ol/info-palet-database}errorGroup"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "row", propOrder = {
    "csoc",
    "frep",
    "npallet",
    "atipo",
    "aorigen",
    "adestino",
    "cpeso",
    "nmonto",
    "nbultos",
    "arut",
    "anombre",
    "adireccion",
    "acomuna",
    "aregion",
    "f12",
    "cnupalet",
    "derror"
})
public class Row {

    @XmlElement(name = "C_SOC")
    protected BigInteger csoc;
    @XmlElement(name = "F_REP")
    protected String frep;
    @XmlElement(name = "N_PALLET")
    protected String npallet;
    @XmlElement(name = "A_TIPO")
    protected String atipo;
    @XmlElement(name = "A_ORIGEN")
    protected String aorigen;
    @XmlElement(name = "A_DESTINO")
    protected String adestino;
    @XmlElement(name = "C_PESO")
    protected BigDecimal cpeso;
    @XmlElement(name = "N_MONTO")
    protected BigDecimal nmonto;
    @XmlElement(name = "N_BULTOS")
    protected BigInteger nbultos;
    @XmlElement(name = "A_RUT")
    protected String arut;
    @XmlElement(name = "A_NOMBRE")
    protected String anombre;
    @XmlElement(name = "A_DIRECCION")
    protected String adireccion;
    @XmlElement(name = "A_COMUNA")
    protected String acomuna;
    @XmlElement(name = "A_REGION")
    protected String aregion;
    @XmlElement(name = "F12")
    protected F12 f12;
    @XmlElement(name = "CNUPALET")
    protected String cnupalet;
    @XmlElement(name = "DERROR")
    protected String derror;
    @XmlAttribute
    protected Integer num;

    /**
     * Gets the value of the csoc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCSOC() {
        return csoc;
    }

    /**
     * Sets the value of the csoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCSOC(BigInteger value) {
        this.csoc = value;
    }

    /**
     * Gets the value of the frep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFREP() {
        return frep;
    }

    /**
     * Sets the value of the frep property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFREP(String value) {
        this.frep = value;
    }

    /**
     * Gets the value of the npallet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPALLET() {
        return npallet;
    }

    /**
     * Sets the value of the npallet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPALLET(String value) {
        this.npallet = value;
    }

    /**
     * Gets the value of the atipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATIPO() {
        return atipo;
    }

    /**
     * Sets the value of the atipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATIPO(String value) {
        this.atipo = value;
    }

    /**
     * Gets the value of the aorigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAORIGEN() {
        return aorigen;
    }

    /**
     * Sets the value of the aorigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAORIGEN(String value) {
        this.aorigen = value;
    }

    /**
     * Gets the value of the adestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADESTINO() {
        return adestino;
    }

    /**
     * Sets the value of the adestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADESTINO(String value) {
        this.adestino = value;
    }

    /**
     * Gets the value of the cpeso property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCPESO() {
        return cpeso;
    }

    /**
     * Sets the value of the cpeso property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCPESO(BigDecimal value) {
        this.cpeso = value;
    }

    /**
     * Gets the value of the nmonto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNMONTO() {
        return nmonto;
    }

    /**
     * Sets the value of the nmonto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNMONTO(BigDecimal value) {
        this.nmonto = value;
    }

    /**
     * Gets the value of the nbultos property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNBULTOS() {
        return nbultos;
    }

    /**
     * Sets the value of the nbultos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNBULTOS(BigInteger value) {
        this.nbultos = value;
    }

    /**
     * Gets the value of the arut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARUT() {
        return arut;
    }

    /**
     * Sets the value of the arut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARUT(String value) {
        this.arut = value;
    }

    /**
     * Gets the value of the anombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANOMBRE() {
        return anombre;
    }

    /**
     * Sets the value of the anombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANOMBRE(String value) {
        this.anombre = value;
    }

    /**
     * Gets the value of the adireccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADIRECCION() {
        return adireccion;
    }

    /**
     * Sets the value of the adireccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADIRECCION(String value) {
        this.adireccion = value;
    }

    /**
     * Gets the value of the acomuna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACOMUNA() {
        return acomuna;
    }

    /**
     * Sets the value of the acomuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACOMUNA(String value) {
        this.acomuna = value;
    }

    /**
     * Gets the value of the aregion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAREGION() {
        return aregion;
    }

    /**
     * Sets the value of the aregion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAREGION(String value) {
        this.aregion = value;
    }

    /**
     * Gets the value of the f12 property.
     * 
     * @return
     *     possible object is
     *     {@link F12 }
     *     
     */
    public F12 getF12() {
        return f12;
    }

    /**
     * Sets the value of the f12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link F12 }
     *     
     */
    public void setF12(F12 value) {
        this.f12 = value;
    }

    /**
     * Gets the value of the cnupalet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNUPALET() {
        return cnupalet;
    }

    /**
     * Sets the value of the cnupalet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNUPALET(String value) {
        this.cnupalet = value;
    }

    /**
     * Gets the value of the derror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDERROR() {
        return derror;
    }

    /**
     * Sets the value of the derror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDERROR(String value) {
        this.derror = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNum(Integer value) {
        this.num = value;
    }

}
