
/*
 * 
 */

package cl.falabella.b2b.intol.ws.client.agendaunica.appointment.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.11
 * Wed Jul 12 16:38:40 GMT-04:00 2017
 * Generated source version: 2.2.11
 * 
 */


@WebServiceClient(name = "AppointmentService", 
                  wsdlLocation = "file:/F:/proyectos/AGENDA_UNICA/CM/PRAGMA_INTOL/files/AppointmentService.wsdl",
                  targetNamespace = "http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0") 
public class AppointmentService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0", "AppointmentService");
    public final static QName AppointmentPort = new QName("http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0", "AppointmentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/proyectos/AGENDA_UNICA/CM/PRAGMA_INTOL/files/AppointmentService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/F:/proyectos/AGENDA_UNICA/CM/PRAGMA_INTOL/files/AppointmentService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AppointmentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppointmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppointmentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns AppointmentPt
     */
    @WebEndpoint(name = "AppointmentPort")
    public AppointmentPt getAppointmentPort() {
        return super.getPort(AppointmentPort, AppointmentPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppointmentPt
     */
    @WebEndpoint(name = "AppointmentPort")
    public AppointmentPt getAppointmentPort(WebServiceFeature... features) {
        return super.getPort(AppointmentPort, AppointmentPt.class, features);
    }

}
