package cl.falabella.b2b.intol.ws.client.agendaunica.appointment.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.11
 * Wed Jul 12 16:38:39 GMT-04:00 2017
 * Generated source version: 2.2.11
 * 
 */
 
@WebService(targetNamespace = "http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0", name = "AppointmentPt")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.client.agendaunica.appointment.beans.req.ObjectFactory.class, cl.falabella.b2b.intol.ws.client.agendaunica.appointment.beans.resp.ObjectFactory.class, cl.falabella.b2b.intol.ws.client.agendaunica.appointment.beans.envelope.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AppointmentPt {

    @WebResult(name = "AppointmentResp", targetNamespace = "http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Resp/v2017.02", partName = "AppointmentRespParam")
    @WebMethod(operationName = "AppointmentOp", action = "http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0/Op")
    public cl.falabella.b2b.intol.ws.client.agendaunica.appointment.beans.resp.AppointmentRespTYPE appointmentOp(
        @WebParam(partName = "AppointmentReqParam", name = "AppointmentReq", targetNamespace = "http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Req/v2017.02")
        cl.falabella.b2b.intol.ws.client.agendaunica.appointment.beans.req.AppointmentReq appointmentReqParam
    ) throws FaultMsg;
}
