package cl.falabella.b2b.intol.ws.infodocumento.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Jul 15 12:19:48 CLT 2011
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/info-documento", name = "InfoDocumentoService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.infodocumento.beans.request.ObjectFactory.class, cl.falabella.b2b.intol.ws.infodocumento.beans.response.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoDocumentoService {

    @WebResult(name = "info-documento-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-documento-response", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.infodocumento.beans.response.InfoDocumentoResponse infoDocumento(
        @WebParam(partName = "request", name = "info-documento-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-documento-request")
        cl.falabella.b2b.intol.ws.infodocumento.beans.request.InfoDocumentoRequest request
    );
}
