package cl.falabella.b2b.intol.ws.trl.validagps.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Fri Nov 06 16:14:31 CLST 2015
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "WM_RETORNA_STATUSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WM_RETORNA_STATUS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WMRETORNASTATUS")
    @ResponseWrapper(localName = "WM_RETORNA_STATUSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WMRETORNASTATUSResponse")
    @WebMethod(operationName = "WM_RETORNA_STATUS", action = "http://tempuri.org/WM_RETORNA_STATUS")
    public java.lang.String wmRETORNASTATUS(
        @WebParam(name = "PATENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String patente,
        @WebParam(name = "ID_CLIENTE", targetNamespace = "http://tempuri.org/")
        int idCLIENTE
    );
}
