<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:tns="http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:req="http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Req/v2017.02" xmlns:resp="http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Resp/v2017.02" xmlns:ns1="http://schemas.xmlsoap.org/soap/encoding/" name="Appointment" targetNamespace="http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0">
  <wsdl:types>
    <xs:schema>
      <xs:import namespace="http://schemas.xmlsoap.org/soap/envelope/" schemaLocation="MdwCorp_Common_soapFault.xsd"/>
      <xs:import schemaLocation="WLS_LOG_CORP_Appointment_Req.xsd" namespace="http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Req/v2017.02"/>
      <xs:import schemaLocation="WLS_LOG_CORP_Appointment_Resp.xsd" namespace="http://mdwcorp.falabella.com/LOG/CORP/WLS/schema/WMOS/Appointment/Resp/v2017.02"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="AppointmentMsgReq">
    <wsdl:part name="AppointmentReqParam" element="req:AppointmentReq"/>
  </wsdl:message>
  <wsdl:message name="AppointmentMsgResp">
    <wsdl:part name="AppointmentRespParam" element="resp:AppointmentResp"/>
  </wsdl:message>
  <wsdl:message name="FaultMsg">
    <wsdl:part name="FaultParam" element="env:Fault"/>
  </wsdl:message>
  <wsdl:portType name="AppointmentPt">
    <wsdl:operation name="AppointmentOp">
      <wsdl:input message="tns:AppointmentMsgReq"/>
      <wsdl:output message="tns:AppointmentMsgResp"/>
      <wsdl:fault name="Fault" message="tns:FaultMsg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AppointmentBinding" type="tns:AppointmentPt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="AppointmentOp">
      <soap:operation soapAction="http://mdwcorp.falabella.com/LOG/CORP/WLS/wsdl/WMOS/Appointment/v1.0/Op"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="Fault">
        <soap:fault name="Fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AppointmentService">
    <wsdl:port name="AppointmentPort" binding="tns:AppointmentBinding">
      <soap:address location="http://localhost"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>