package cl.falabella.b2b.intol.ws.agendaventaverde.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-01T14:58:31.961-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/agenda-ventaverde", name = "AgendaVerdeService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.agendaventaverde.beans.consmuelles.ObjectFactory.class, cl.falabella.b2b.intol.ws.agendaventaverde.beans.agenda.ObjectFactory.class, cl.falabella.b2b.intol.ws.agendaventaverde.beans.consventanas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgendaVerdeService {

    @WebResult(name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-ventanas", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.agendaventaverde.beans.consventanas.Archivo consultaVentanas(
        @WebParam(partName = "request", name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-ventanas")
        cl.falabella.b2b.intol.ws.agendaventaverde.beans.consventanas.Archivo request
    );

    @WebResult(name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-agenda", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.agendaventaverde.beans.agenda.Archivo reservaAgenda(
        @WebParam(partName = "request", name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-agenda")
        cl.falabella.b2b.intol.ws.agendaventaverde.beans.agenda.Archivo request
    );

    @WebResult(name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-muelles", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.agendaventaverde.beans.consmuelles.Archivo consultaAgendaActual(
        @WebParam(partName = "request", name = "Archivo", targetNamespace = "http://b2b.falabella.com/schemas/ol/ventaverde-muelles")
        cl.falabella.b2b.intol.ws.agendaventaverde.beans.consmuelles.Archivo request
    );
}
