package cl.falabella.b2b.intol.ws.trl.viaje.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.11
 * Fri Jan 24 11:33:53 CLST 2014
 * Generated source version: 2.2.11
 * 
 */
 
@WebService(targetNamespace = "http://b2b.falabella.com/service/ol/info-viaje", name = "InfoViajeService")
@XmlSeeAlso({cl.falabella.b2b.intol.ws.trl.viaje.bean.response.ObjectFactory.class, cl.falabella.b2b.intol.ws.trl.viaje.bean.request.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoViajeService {

    @WebResult(name = "info-viaje-response", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-viaje-response", partName = "response")
    @WebMethod
    public cl.falabella.b2b.intol.ws.trl.viaje.bean.response.InfoViajeResponse informarViaje(
        @WebParam(partName = "request", name = "info-viaje-request", targetNamespace = "http://b2b.falabella.com/schemas/ol/info-viaje-request")
        cl.falabella.b2b.intol.ws.trl.viaje.bean.request.InfoViajeRequest request
    );
}
